get:
  tags: [ PatronRequests ]
  description: "List the tokens that will be used for the notice token values"
  operationId: patronrequestsNoticeTokenValues
  parameters:
    - $ref: '../../parameters/path/id.yaml'
  responses:
    '200':
      description: Successful response
      content:
        application/json: {}
    '400':
      $ref: '../../error-responses/BadRequest.yaml'
    '404':
      $ref: '../../error-responses/NotFound.yaml'
    '500':
      $ref: '../../error-responses/InternalServerError.yaml'
